spring:
  datasource:
    url: jdbc:h2:mem:bookstoredb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  h2:
    console:
      enabled: true

jwt:
  secret: myVerySecretKeyForBookstoreApplication123456
  expiration: 86400000